### PR TITLE
Update to new lib-common VolumeSource structs

### PR DESCRIPTION
**Pull request by dprince**

### CODE REVIEW

**Comment by fmount** [comment]
Added the dependency on https://github.com/openstack-k8s-operators/openstack-operator/pull/1158 so that the `Prow` job can checkout that particular `PR` instead of using `main`

**Comment by fmount** [comment]
@dprince rdoproject/github-check needs https://github.com/openstack-k8s-operators/openstack-operator/pull/1158 to merge first (because the dependency works the other way around).
However, the great news is that we can see extraMounts properly rendered [1], and the Pods w/ the right Ceph mounts [2], which proves it works as expected.
I'm removing the Depends-On from the description and wait for a recheck of this patch (but it's the very same for cinder/glance/neutron/etc) when `1158` merges!

[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_manila-operator/350/pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1853490938882560000/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-3d1f620ae3617fbd6371f55aa948b34e9daf31a461d3c557cf1a7c2db38d0385/namespaces/openstack/crs/manilas.manila.openstack.org/manila.yaml

[2]https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_manila-operator/350/pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1853490938882560000/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-3d1f620ae3617fbd6371f55aa948b34e9daf31a461d3c557cf1a7c2db38d0385/namespaces/openstack/pods/manila-share-share1-0/manila-share-share1-0-describe

**Comment by dprince** [comment]
recheck

**Review by fmount — APPROVED** [review]
/lgtm

**Pull request merged**
