### PR TITLE
Webhook for default images

### PR DESCRIPTION
**Pull request by abays**
Default container images are now handled via env vars and internal webhooks. This defaulting logic will in turn later be integrated with OpenStack Operator via webhooks there that use the new defaulting mechanism (while at the same time disabling the Manila service operator internal webhooks in that context).

### CODE REVIEW

**Review by fmount — APPROVED** [review]
Looks good, pretty much same approach we have in Cinder.

**Comment by fmount** [comment]
@abays are you going to follow up here [1] and update the `openstack-operator` when manila is `enabled`?


[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/master/apis/core/v1beta1/openstackcontrolplane_webhook.go

**Comment by abays** [comment]
> @abays are you going to follow up here [1] and update the `openstack-operator` when manila is `enabled`?
> 
> [1] https://github.com/openstack-k8s-operators/openstack-operator/blob/master/apis/core/v1beta1/openstackcontrolplane_webhook.go

Yes, I will be doing that.  I also have to add logic for all the operators referenced in these files [1], once they themselves have their specific defaulting logic added.  I've been going through that list and adding the webhooks/logic and should hopefully be done soon.

[1] https://github.com/openstack-k8s-operators/openstack-operator/tree/master/pkg/openstack

**Comment by fmount** [comment]
Thanks for the help there, that makes sense!

**Pull request merged**
