### PR TITLE
Add DHSS related example

### PR DESCRIPTION
**Pull request by fmount**
This patch improves the backends section adding the netapp-dhss one. In addition, it fixes the whole samples by adding the missing bases/openstack sample referenced everywhere.

### CODE REVIEW

**Comment by fmount** [comment]
We might want to  follow up on the `README` and describe something relevant for each backend. @gouthampacha maybe you can help on that front because we need to specify additional manila commands, but I would do that in a follow up change.

**Review by gouthampacha — APPROVED** [review]
great; thanks @fmount .. lgtm. I agree with the readme comment; i'll follow up in a different change

**Pull request merged**
