### PR TITLE
[envtest]Use keystone helpers from keystone-operator

### PR DESCRIPTION
**Pull request by gibizer**
This was necessary to remove a dependency cycle from lib-common

### CODE REVIEW

**Comment by gibizer** [comment]
/test manila-operator-build-deploy-tempest

It seems manila-api is not exposed via a route:
```
  manilaAPI:
    containerImage: quay.io/podified-antelope-centos9/openstack-manila-api@sha256:02a022e2db1d6bf6d5667306ed3fd3b66399ead919894a3dba8e85e8bfd7a2d7
    customServiceConfig: '# add your customization here'
    debug:
      service: false
    override:
      service:
        internal:
          metadata:
            labels:
              service: manila
        public:
          metadata:
            labels:
              service: manila
```

**Comment by gibizer** [comment]
Same error ManilaAPI does not have an EndpointURL set so it is not exposed
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_manila-operator/141/pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1706326355802591232/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-070a98749455b097c66a1a25ff827a3c0ee7385f1f0c8bf54f5b15438501f2bd/namespaces/openstack/crs/manilaapis.manila.openstack.org/manila-api.yaml 

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_manila-operator/141/pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1706326355802591232/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-070a98749455b097c66a1a25ff827a3c0ee7385f1f0c8bf54f5b15438501f2bd/namespaces/openstack/routes/

**Review by fmount — APPROVED** [review]

**Pull request merged**
