### PR TITLE
Add minumum validation for DBPurge Age

### PR DESCRIPTION
**Pull request by fmount**

### CODE REVIEW

**Comment by fmount** [comment]
Mostly checking if zuul/kuttl does the right thing when we have an API change.

**Comment by fmount** [comment]
We still have a problem when we run the `ci-framework` kuttl job.
The `manifest` that results in the new CRD ($subject of this change) is not used:

```
dbPurge:
  properties:
    age:
      default: 30
      type: integer
      schedule:
      default: 1 0 * * *
      type: string
```
while if we look at the `Prow` (tempest) based job, the `CRD`  looks updated:

```
dbPurge:
  properties:
    age:
      default: 30
      minimum: 1
      type: integer
      schedule:
      default: 1 0 * * *
      type: string
```


[1]  https://logserver.rdoproject.org/97/197/f60f01ed674b1c6e3bce6d93de9500dc03fad851/github-check/manila-operator-kuttl/974bd37/controller/ci-framework-data/logs/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-206e6f463855943ce5f128d1731718c7a7e0faf5bb2cc0fda0ddeb567abeb18d/crd/manilas.manila.openstack.org.yaml

[2]  https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_manila-operator/197/pull-ci-openstack-k8s-operators-manila-operator-main-manila-operator-build-deploy-tempest/1737101420466802688/artifacts/manila-operator-build-deploy-tempest/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-206e6f463855943ce5f128d1731718c7a7e0faf5bb2cc0fda0ddeb567abeb18d/crd/manilas.manila.openstack.org.yaml

**Comment by fmount** [comment]
@viroel ok I think I know what's going on there.
`content-provider` rebuild `manila-operator` and the associated bundle based on this patch, which is correct [1]:
```
Successfully tagged 38.129.56.100:5001/openstack-k8s-operators/manila-operator-bundle:f60f01ed674b1c6e3bce6d93de9500dc03fad851
d23b206f20a8196985cf1484b7e375a36288ae62e844f6a489ed5a651975c249
```
However, the `manila_kuttl` target executed by the `makefile` uses the current tag (see events [2]):
```
Pulling image "quay.io/openstack-k8s-operators/manila-operator-bundle:1cb98fa5ea4ce8d58782330bf21106f828f6f7af"`
```

and this is the reason we see the old `manifest` in the job.

[1] https://logserver.rdoproject.org/97/197/f60f01ed674b1c6e3bce6d93de9500dc03fad851/github-check/openstack-k8s-operators-content-provider/d6fe5bb/ci-framework-data/logs/ci_make_005_manila-operator_-_call_bundle-build.log
[2] https://logserver.rdoproject.org/97/197/f60f01ed674b1c6e3bce6d93de9500dc03fad851/github-check/manila-operator-kuttl/974bd37/controller/ci-framework-data/logs/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-206e6f463855943ce5f128d1731718c7a7e0faf5bb2cc0fda0ddeb567abeb18d/namespaces/openstack-operators/events.log

**Comment by fmount** [comment]
@gouthampacha this is good to go

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
