### PR TITLE
Unpin openstack-k8s-operators

### PR DESCRIPTION
**Pull request by kajinamit**
We pinned these to the released versions for the dev preview release but we should resume tracking the latest code.

### CODE REVIEW

**Comment by kajinamit** [comment]
Looks like kuttl job is broken and we need to merge https://github.com/openstack-k8s-operators/manila-operator/pull/122 first.

**Comment by fmount** [comment]
> Looks like kuttl job is broken and we need to merge #122 first.

Right, I'll recheck this one as long as the CI is green.

**Comment by fmount** [comment]
@kajinamit you should probably rebase this patch on main to get the kuttl fix

**Comment by kajinamit** [comment]
> @kajinamit you should probably rebase this patch on main to get the kuttl fix

I guess we don't need rebase, but it does not harm, so I rebased this on top on the latest main.

**Review by fmount — APPROVED** [review]

**Pull request merged**
