### PR TITLE
Use time.Duration for timeout

### PR DESCRIPTION
**Pull request by kajinamit**
instead of int. This allows us to use more fine grained timeout value such as 0.1, and encodes the unit in the type itself.

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/155
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/166

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

Not sure what's going on with the checks though

**Comment by abays** [comment]
@kajinamit Could the linting failures be due to a missing execution of `go mod tidy` before pushing?

**Comment by kajinamit** [comment]
It was my fault. I had to comment out openshift in go.mod to get `go get` happy but I forgot to remove the heading `//` before subimitting PR. I fixed that.

**Comment by kajinamit** [comment]
Hmm. I looked into the lint error, but it seems these are the bugs/problems which are already there in current code it seems. I'll look into these tomorrow when I have time but these should be fixed separately.

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
